// <auto-generated />
namespace CandidateScreening.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddingAddressClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingAddressClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201507211203177_AddingAddressClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
